require_paths:
- "C:/Program Files/SketchUp/SketchUp 2020/Tools"
- "C:/Program Files/SketchUp/SketchUp 2019/Tools"
- "C:/Program Files/SketchUp/SketchUp 2018/Tools"
- src

require:
- sketchup-api-stubs

reporters:
- rubocop

exclude:
- /build/**/*
